[profile.default]
src = "contracts/src"
out = "out"
libs = ["node_modules", "lib"]
test = "contracts/test"
script = "contracts/script"
cache_path = "cache"

remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@layerzerolabs/=node_modules/@layerzerolabs/",
    "solidity-bytes-utils/=node_modules/solidity-bytes-utils/",
    "forge-std/=lib/forge-std/src/"
]
